### ISSUE TITLE
Install Now to Netlify failing with 'page not found'

### ISSUE THREAD

**Issue by davidtew** [drehimself/gridsome-portfolio-starter#24]
To my untrained mind, everything looks OK after Install Now (from https://gridsome.org/starters/gridsome-portfolio-starter).  

Upon clicking the site link in Netlify I am seeing 'Page Not Found' rather than a site. (other installed Gridsome starter sites work ok).

**Comment by drehimself** [comment]
Thanks for letting me know.

Fixed by creating a `netlify.toml` file: https://github.com/drehimself/gridsome-portfolio-starter/commit/ab12c3b94f79d0c9e56360fb38bbb8bf26b07852

This automatically adds the site settings (build command and publish directory) in netlify.

![netlify_settings](https://user-images.githubusercontent.com/4316355/63284301-35c23300-c281-11e9-9d1b-98e33f490aff.png)
