### ISSUE TITLE
Move RSS & Search into gitignore

### ISSUE THREAD

**Issue by ndalliard** [drehimself/gridsome-portfolio-starter#3]
Shouldn't we put `static/sitemap.xml` and `static/search.json` into `.gitignore` cause both are generated? Can provide you with a PR if you want. But the change is really small.

**Comment by drehimself** [comment]
Technically, yes. 

I've added `static/rss.xml` to `.gitignore`

However, I'm going to leave `search.json` in there because when someone is just working locally using `gridsome develop` the search won't work unless a `search.json` exists in the `static` folder. This could lead to some confusion for anyone who is playing around with the repo locally.

If this was a real production site (and not an example repo), I would probably `.gitignore` it (after I've tested it and know it works).
