### ISSUE TITLE
Incorporate Docs in Fuse Search

### ISSUE THREAD

**Issue by marcodeluca** [drehimself/gridsome-portfolio-starter#84]
Thanks for the starter, using it as an intro to gridsome and tailwind. Quick question, any suggestions on how to incorporate multiple content types into a single search? For example:

`const { collection } = store.getContentType('Post', 'Documentation');`

But then there would have to be I guess some more complex joining after that... it's all new to me so if there's an easy way to do this I'd love to see an example.

Thanks!

**Comment by drehimself** [comment]
Hmm, I thought it would be that simple but since Documentation is a different type than Post (Posts use the `source-filesystem` plugin, Docs use the `vue-remark` plugin), I'm not sure how to grab the docs in the `gridsome.server.js` file

`gridsome.server.js`
```js
const { collection } = store.getContentType('Post'); // grabs posts, works

 // doesn't work for vue-remark types, not sure how to grab docs
const { collectionDocs } = store.getContentType('Documentation');
```

If you're reading this and you know, please let me know. Or better yet, send a PR!
